### ISSUE TITLE
Add adapter-fabric module

### ISSUE THREAD

**Issue by i509VCB** [KyoriPowered/adventure-platform#11]
This would be another adapter to convert Kyori's text format to the Text format which fabric uses.

I will probably submit a draft of it later. This probably won't be much larger than a single helper class since the Text system fabric uses (which is minecraft's native system already has a built in serializer).

**Comment by zml2008** [comment]
As mentioned in #12, adventure has grown a bit since this was posted, so we now have a [separate fabric platform](https://github.com/KyoriPowered/adventure-platform-fabric).
