### ISSUE TITLE
ViaFacet isn't being consistently used when it is the best applicable approach.

### ISSUE THREAD

**Issue by Fabelz** [KyoriPowered/adventure-platform#130]
There's an issue with the way that the viafacet is currently being handled as it doesn't attempt to re-establish usage of itself if a player's userconnection is temporarily unavailable. This also affects other players that are a part of the same audience as well, as it seems to not care about picking a new facet on a per player basis.

This leads to various issues with message formatting, as it will not attempt to format the message properly with post-1.16 and whatnot formatting changes.

To replicate:
- Join a server (preferably one that is pre-1.16), have it send a message on login.
- Send a message.
- Keep relogging, and it'll eventually break.

How the message should look (on 1.19 for both images):
![image](https://user-images.githubusercontent.com/15955937/234300914-14c3c2bc-18a9-4cd1-973f-a0d9e2308527.png)
How it ends up looking (downsampled to the pre-1.16 message formatting due to it being permanently unable to tell the client's version):
![image](https://user-images.githubusercontent.com/15955937/234301048-c3b9342c-5d58-484f-aa8a-1bdd56e88fa6.png)

**Comment by Fabelz** [comment]
This issue needs to be reopened as it is still not fixed. Regardless of the ViaVersion configuration option "register-userconnections-on-join" being true or false this is still easily replicatable on the latest stable viaversion and viafacet platform versions as the user connection can still be null at times.  @Pablete1234 @kashike 

The issues mentioned were also merged in to viaversion 8 months prior to me making the initial issue report, and the configuration option has never been set to off.

I think that this could be potentially due to these specific messages being sent by our redis listener receiving a message to send those messages pre- join event, but regardless, it's something that still needs fixing imo.

**Comment by kezz** [comment]
Can you verifiably reproduce this without your redis listener situation?

**Comment by Pablete1234** [comment]
A couple things to point out:
> The issues mentioned were also merged in to viaversion 8 months prior to me making the initial issue report
The latest one had just been merged

> I think that this could be potentially due to these specific messages being sent by our redis listener receiving a message to send those messages pre- join event
Yeah, if you're using stuff before the join event you're still going to see the race condition occur, but this is on viaversion.
Consider switching to join event instead

**Comment by Fabelz** [comment]
> 
in this specific use case scenario, the message has a chance of being sent _before the player technically joins_, this doesn't necessarily mean that it's sparked by that player joining as the message is received to be sent from an alternative thread, and other messages could also be sent from this regard, regardless of them being connection messages or not. There's no way to verify if the player has properly joined yet, short of quite literally creating a check for every player to see if they have joined, therefore still making this an issue.

**Comment by Fabelz** [comment]
> Can you verifiably reproduce this without your redis listener situation?

All you'd need to do is send a message to a player _before_ the join event (although I'm not 110% sure that the join event scenario is foolproof itself as I swear I've seen it happen there before, it's just harder to reproduce). The reason that this is an issue is because minecraft chat is, itself, literally supposed to be asynchronous. I understand that the player cannot have their version be told 24/7, that's perfectly alright, but the way that once that happens the ViaFacet doesn't even _attempt_ to ever reverify their connection is a problem, as it can impact everybody's ability to see fancier formatting from 1.16 and above as well, as it cannot be fixed until a server restart.

**Comment by kezz** [comment]
Doing stuff with the player before the join event isn't and never has been supported. ViaVersion specifically doesn't initialise various parts until the join event, meaning there's nothing we can do here.

I'd suggest just delaying any message sending until after the join event, or at least doing it on the priority mentioned in Pablete's comment.

**Comment by Fabelz** [comment]
The problem isn't that I can't send it at that time though -- I genuinely wouldn't even care if the message didn't get sent to the player at all, it's the fact that if I were to send it globally (not even to the specific player in question) at any point in time from another thread, and a player was to be between the login and join states it would perform this bug. The user connection doesn't get re-established at all for any player from then on out due to the way that audiences work.

**Comment by Pablete1234** [comment]
From what you describe, your issue is purely one of thread safety then.
Schedule your message-sending on the mainthread, consider sending from other threads not supported
