### ISSUE TITLE
Bug Report: Invalid Legacy Formatting Warning Specifically with sendActionBar in Older Minecraft Versions

### ISSUE THREAD

**Issue by Bram1903** [KyoriPowered/adventure-platform#155]
**Description:**
When utilizing the Adventure library's `sendActionBar` method in a Bukkit plugin on older Minecraft versions (1.8 in this example), a warning related to legacy formatting codes is being erroneously thrown. This warning is specific to the `sendActionBar` method and does not occur with other methods such as `sendMessage` or `sendTitle`. Despite not employing any legacy formatting codes in the codebase, the warning persists, indicating a potential issue within the Adventure library's implementation for older Minecraft versions.

**Steps to Reproduce:**
1. Install the provided plugin on a Minecraft server running version 1.8.
2. Execute the command associated with the plugin that triggers the `sendActionBar` method, e.g., `/showcase`.
3. Observe the console logs for warnings related to legacy formatting codes.

**Repository including a showcase project:** [AdventureBugExample](https://github.com/Bram1903/AdventureBugExample)

The plugin can easily be tested by running `gradle runServer`. This will fire up a paper server running 1.8.8, with the latest build of the plugin.

**Expected Behavior:**
The `sendActionBar` method should execute without any warnings related to legacy formatting codes, similar to other message-sending methods such as `sendMessage` and `sendTitle`.

**Actual Behavior:**
Warnings related to legacy formatting codes are specifically thrown when utilizing the `sendActionBar` method, despite the absence of legacy formatting codes in the codebase. Other message-sending methods do not trigger these warnings.

**Additional Information:**
- This issue is not reproducible in version 1.20.4 of Minecraft.
- The warning specifically occurs with the `sendActionBar` method, suggesting a potential discrepancy or bug in its implementation for older Minecraft versions.

**Environment:**
- Minecraft Version: 1.8
- Server Software: Paper
- Adventure Library Version (Bukkit): 4.3.2
- Operating System: Windows

**Possibly related to #86**

**Comment by zml2008** [comment]
There's a client bug in older Minecraft versions that causes the client to not properly handle components sent to the action bar, the legacy text there us a workaround. iirc the legacy warning is gated behind a system property, so just don't enable it if you're working in legacy environments
