### ISSUE TITLE
Empty page content on 1.20.4

### ISSUE THREAD

**Issue by Emibergo02** [KyoriPowered/adventure-platform#169]
![Wacxdgj](https://github.com/KyoriPowered/adventure-platform/assets/36164338/cc5d7a8e-d009-43ba-8d36-003855093756)
With paper API (content isn't null or empty , it is "Mail Content")
```java
        final ItemStack writtenBook = new ItemStack(Material.WRITTEN_BOOK);
        writtenBook.setItemMeta(((BookMeta) writtenBook.getItemMeta())
                .toBuilder()
                .addPage(manager.getPlugin().getComponentProvider().parse(content))
                .build());
        player.openBook(writtenBook);
```
With Adventure (content isn't null or empty , it should say "Mail Content")
```java
        bukkitAudiences.player(player).openBook(
                Book.builder()
                        .addPage(manager.getPlugin().getComponentProvider().parse(content))
                        .build());
```
I have the latest version of paper and adventure

**Comment by kezz** [comment]
If you're using the latest version of Paper why are you using adventure-platform? Paper has shipped with Adventure for years now.

**Comment by Emibergo02** [comment]
The second one is with adventure-platform. but now i am thinking that this is the wrong repo to open this kind of issue

**Comment by kezz** [comment]
I'm a bit confused about what the issue is here. Are you saying that adventure-platform's `openBook` method is not working on 1.20.4?

**Comment by kezz** [comment]
Well who knows now
