### ISSUE TITLE
Actionbar not working with platform bukkit 1.20.5+

### ISSUE THREAD

**Issue by itsme-to** [KyoriPowered/adventure-platform#172]
Simply run

```java
plugin.adventure().player(player).sendActionBar(*insert component here*);
```
It does work everywhere except for Spigot & Paper 1.20.6 when using platform

**Comment by powercasgamer** [comment]
Cannot reproduce on Spigot `4179-Spigot-342f493-bdb40c5` or Paper `1.20.6-130-master@5d8e53d`. using `implementation("net.kyori:adventure-platform-bukkit:4.3.3")`

**Comment by kezz** [comment]
Ensure you're running on the latest build as it looks fine
