### ISSUE TITLE
Some features don't work in version 1.20.6

### ISSUE THREAD

**Issue by Syrent** [KyoriPowered/adventure-platform#175]
#### Description
Some features, such as `sendActionbar`, `openBook`, and clickable components, are not working on Minecraft version 1.20.6.

#### Steps Taken
1. Updated all Adventure dependencies to the latest versions:
    - `adventure-api`: 4.17.0
    - `adventure-platform-bukkit`: 4.3.3
    - `adventure-text-minimessage`: 4.17.0
2. Relocated packages from `net.kyori` to `<my-plugin-package-path>.kyori.adventure`.
3. Tested with both relocated and non-relocated versions.
4. Verified with the latest Paper build:
    ```
    This server is running Paper version 1.20.6-137-master@bd5867a (2024-06-04T21:04:28Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
    You are running the latest version
    Previous version: 1.20.6-131-ac64751 (MC: 1.20.6)
    ```

**Comment by powercasgamer** [comment]
Still unable to reproduce https://github.com/KyoriPowered/adventure-platform/issues/172

**Comment by Syrent** [comment]
After setting up a [clean project](https://github.com/Syrent/AdventureTest) where the features worked correctly, I conducted further investigation to identify the problem.

**Investigation Steps:**
1. Created a clean project to isolate the issue.
2. Verified that the Adventure features worked in the clean project setup.
3. Attempted different troubleshooting steps.
4. Finally, reproduced the issue using my API that implements Adventure.

I have an API called [StickyNote](https://github.com/Sayan-Development/StickyNote), which implements [Adventure (latest version)](https://github.com/Sayan-Development/StickyNote/blob/master/buildSrc/src/main/kotlin/org/sayandev/Repositories.kt#L177) and relocates `net.kyori` to `org.sayandev.stickynote.lib.kyori`. I included this API in another project using Gradle dependencies:

```kotlin
implementation("org.sayandev:stickynote-bukkit:1.0.38")
```

I attempted to send the component as shown [here](https://github.com/Syrent/AdventureTest/blob/master/src/main/java/org/sayandev/AdventureTest.java), but features like `sendActionbar` or hover do not work.

**Observations:**
- The issue is not present in the StickyNote API itself, as all dependencies are up-to-date
- The features work in all versions except for 1.20.6
- There seems to be a specific problem with Adventure on version 1.20.6
- I suspect that the issue comes from relocating Adventure inside StickyNote and then using StickyNote relocations in other projects

**Comment by Syrent** [comment]
The problem has been resolved. I had implemented Adventure in multiple modules, and consolidating it into a single module solved the issue. I'm unsure why this worked in older versions but caused problems in version 1.20.6. However, the issue is now resolved.
