### ISSUE TITLE
ComponentSerializer add bracket to item names

### ISSUE THREAD

**Issue by Elikill58** [KyoriPowered/adventure-platform#185]
(Only tested on spigot 1.20.4 & more)

When using `LegacyComponentSerializer.legacySection().serialize(input)` and `PlainTextComponentSerializer.legacySection().serialize(input)`, there is bracket that appear.

So, instead of having "Name", you have "[Name]". Example:

![image](https://github.com/user-attachments/assets/ef2df193-02ce-4359-875a-28286d892978)

![image](https://github.com/user-attachments/assets/c33e8d74-06a1-43d4-ba22-1e0942d8aed5)

Full reproductible code:
```java
ItemStack item = p.getItemInHand();
p.sendMessage("Test: " + item.getItemMeta().getDisplayName() + ", legacy: " + LegacyComponentSerializer.legacySection().serialize(item.displayName()));
```

**Comment by powercasgamer** [comment]
This is not an Adventure issue, see [this pull request](https://github.com/PaperMC/Paper/pull/9050) for more info
