### ISSUE TITLE
ProtocolSupport compatability

### ISSUE THREAD

**Issue by Vankka** [KyoriPowered/adventure-platform#26]
https://www.spigotmc.org/resources/protocolsupport.7201/ for down sampling colors for older version users, https://github.com/ProtocolSupport/ProtocolSupport/tree/master/src/protocolsupport/api https://github.com/ProtocolSupport/ProtocolSupport/blob/master/src/protocolsupport/api/ProtocolSupportAPI.java#L36

**Comment by zml2008** [comment]
Downsampling is the job of ProtocolSupport, just like it is for ViaBackwards.

The only reason we specifically integrate with ViaVersion is because it allows newer clients to connect to older servers -- so we have to bypass the server's data structures entirely to send components unmodified.
