### ISSUE TITLE
Can I use the Crafty Reflection Utility in my Own Plugin?

### ISSUE THREAD

**Issue by fracturx** [KyoriPowered/adventure-platform#29]
i noticed on the top of the file is an mit license info thing. if i wanted to include this in my own plugin, do i need to declare it under a new package namespace or can i use my own? from what im getting from the notice, i just need to paste it on the top of the file.

**Comment by kashike** [comment]
Yes, but you must change the package of the class to one of your own: `net.kyori` is not your package to be putting things in.

This project uses the MIT license, so:
- the [license file](https://github.com/KyoriPowered/adventure-platform/blob/master/license.txt) must be included in your repository and distributed (inside any JARs, for example) with your project (naming it `adventure-platform.license.txt` or similar)
- the [header](https://github.com/KyoriPowered/adventure-platform/blob/master/platform/bukkit/src/main/java/net/kyori/adventure/platform/bukkit/Crafty.java#L1-L23) must be kept at the top of the source file, unmodified

Please let us know if you have any more questions.

**Comment by fracturx** [comment]
Thanks, but I noticed you explicitly mentioned for the license file to be inside any distributions. In the case of jars, would I put the license file inside of say src/main/resources?

**Comment by kashike** [comment]
@fracturx Generally people throw the license in the root of the JAR, but `src/main/resources` is fine too - as long as it is included.

**Comment by fracturx** [comment]
I see, thanks for the help!
