### ISSUE TITLE
Empty translatable components in console

### ISSUE THREAD

**Issue by YouHaveTrouble** [KyoriPowered/adventure-platform#35]
Component#translatable does not behave the same in minecraft client and server console.

For example:

       message = Component.translatable(
              "commands.gamemode.success.other",
               NamedTextColor.WHITE,
               Component.text(player.getDisplayName()),
               Component.translatable("gameMode."+gamemode.toString().toLowerCase())
        );
        bukkitAudiences.sender(sender).sendMessage(message);

This results in "Set [playername]'s game mode to [gamemodename]" in client, but displays as empty string in the console ignoring the fact that console has the same ability to translate components as client, which is proven by using bungeecord API

         TranslatableComponent component = new TranslatableComponent("commands.gamemode.success.other", 
         player.getDisplayName(), new TranslatableComponent("gameMode."+gamemode.toString().toLowerCase()));
         sender.sendMessage(component);

This returns "Set [playername]'s game mode to [gamemodename]" both in client and console.

I don't know what exactly goes wrong, but components behaving differently in console and client are not expected.

**Comment by KingOfSquares** [comment]
What if you send it directly to the console?

`bukkitAudiences.console().sendMessage(message)`

**Comment by YouHaveTrouble** [comment]
same output as .sender
