### ISSUE TITLE
api v4.9.1: java.lang.NoSuchFieldError: LOCALE

### ISSUE THREAD

**Issue by cyberpwnn** [KyoriPowered/adventure-platform#61]
The latest dependencies are having issues working all of the sudden, please look at #60

**Comment by kezz** [comment]
Do not open multiple issues with the same question. Please look at my response on that issue and come to the Discord (see the link in the readme) if you need further support.

You are depending on 4.8.0 somehow, most likely through MiniMessage.

**Comment by cyberpwnn** [comment]
> Do not open multiple issues with the same question. Please look at my response on that issue and come to the Discord (see the link in the readme) if you need further support.
> 
> You are depending on 4.8.0 somehow, most likely through MiniMessage.

Exactly how should I declare 4.9.1 if declaring 4.9.1 doesnt declare 4.9.1?

**Comment by kezz** [comment]
> Come to the Discord (see the link in the readme) if you need further support.
