### ISSUE TITLE
Add support for sending screen titles to players

### ISSUE THREAD

**Issue by bloodmc** [KyoriPowered/adventure-platform#9]
Currently there is no way to send a screen title to a player.

https://minecraft.gamepedia.com/Commands/title

Would be nice to have this feature =)

**Comment by bloodmc** [comment]
Any update? =)

**Comment by Electroid** [comment]
@kashike Any appetite for this? Your `text` library is wonderful, but the lack of title support is a big hurdle for us.

**Comment by kashike** [comment]
@Electroid This is a feature I want to add, but I have been a bit busy. I will see if I can get something done.

**Comment by kashike** [comment]
I got some things done, but I need to get ready for work now. Anyone is free to PR to these branches to help:

https://github.com/KyoriPowered/text/compare/feature/title
https://github.com/KyoriPowered/text-extras/compare/feature/title

**Comment by Electroid** [comment]
This is done now :)
