### ISSUE TITLE
HoverComponents do not work on 1.19

### ISSUE THREAD

**Issue by Artemis-the-gr8** [KyoriPowered/adventure-platform#92]
Tested on Spigot 1.19 with vanilla client, and no other plugins present than my own. 
Hex colors, and normal text components all work fine, but hover text simply does not show.

Below is the server log with debugging enabled:
https://paste.gg/p/anonymous/67a2aa098a9d47b7871db9684420b1c1

**Comment by zml2008** [comment]
There probably needs to be support added for 1.19 internals changes. Feel free to PR.
